// <auto-generated />
using System;
using CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260819184504_InitialPortfolioSchema")]
    partial class InitialPortfolioSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portfolio")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.CorporateClientModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LogoReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_reference");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility_status");

                    b.HasKey("Id")
                        .HasName("pk_corporate_client");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_corporate_client_name");

                    b.HasIndex("VisibilityStatus")
                        .HasDatabaseName("ix_corporate_client_visibility_status");

                    b.ToTable("corporate_client", "portfolio", t =>
                        {
                            t.HasCheckConstraint("ck_corporate_client_logo_reference", "length(btrim(logo_reference)) > 0");

                            t.HasCheckConstraint("ck_corporate_client_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_corporate_client_visibility_status", "visibility_status IN ('VISIBLE', 'HIDDEN')");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.MediaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cover");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex(new[] { "ProjectId" }, "ix_media_project_id");

                    b.HasIndex(new[] { "ProjectId" }, "uq_media_project_cover")
                        .IsUnique()
                        .HasFilter("is_cover = true");

                    b.ToTable("media", "portfolio", t =>
                        {
                            t.HasCheckConstraint("ck_media_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_media_reference", "length(btrim(reference)) > 0");

                            t.HasCheckConstraint("ck_media_type", "type IN ('IMAGE', 'VIDEO')");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.ProjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CorporateClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("corporate_client_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publication_status");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_project_category_id");

                    b.HasIndex("CorporateClientId")
                        .HasDatabaseName("ix_project_corporate_client_id");

                    b.HasIndex("PublicationStatus")
                        .HasDatabaseName("ix_project_publication_status");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_project_service_id");

                    b.HasIndex("PublicationStatus", "ServiceId", "CategoryId")
                        .HasDatabaseName("ix_project_publication_status_service_id_category_id");

                    b.ToTable("project", "portfolio", t =>
                        {
                            t.HasCheckConstraint("ck_project_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_project_period", "end_date >= start_date");

                            t.HasCheckConstraint("ck_project_publication_status", "publication_status IN ('DRAFT', 'PUBLISHED')");

                            t.HasCheckConstraint("ck_project_published_title", "publication_status <> 'PUBLISHED' OR (title IS NOT NULL AND length(btrim(title)) > 0)");

                            t.HasCheckConstraint("ck_project_title", "title IS NULL OR length(btrim(title)) > 0");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.MediaModel", b =>
                {
                    b.HasOne("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.ProjectModel", "Project")
                        .WithMany("Media")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.ProjectModel", b =>
                {
                    b.HasOne("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.CorporateClientModel", "CorporateClient")
                        .WithMany("Projects")
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_project_corporate_client");

                    b.Navigation("CorporateClient");
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.CorporateClientModel", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Portfolio.Infrastructure.Persistence.Models.ProjectModel", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
