// <auto-generated />
using System;
using CromaticaCreativa.Modules.Services.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CromaticaCreativa.Modules.Services.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServicesDbContext))]
    [Migration("20260819184300_InitialServicesSchema")]
    partial class InitialServicesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("services")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CromaticaCreativa.Modules.Services.Infrastructure.Persistence.Models.CategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ReferenceImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_image");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_category_status");

                    b.HasIndex("ServiceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_category_service_id_name");

                    b.HasIndex("ServiceId", "Status")
                        .HasDatabaseName("ix_category_service_id_status");

                    b.ToTable("category", "services", t =>
                        {
                            t.HasCheckConstraint("ck_category_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_category_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_category_reference_image", "length(btrim(reference_image)) > 0");

                            t.HasCheckConstraint("ck_category_status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Services.Infrastructure.Persistence.Models.ServiceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_reference");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_service_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_status");

                    b.ToTable("service", "services", t =>
                        {
                            t.HasCheckConstraint("ck_service_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_service_image_reference", "length(btrim(image_reference)) > 0");

                            t.HasCheckConstraint("ck_service_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_service_status", "status IN ('ACTIVE', 'INACTIVE')");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Services.Infrastructure.Persistence.Models.CategoryModel", b =>
                {
                    b.HasOne("CromaticaCreativa.Modules.Services.Infrastructure.Persistence.Models.ServiceModel", "Service")
                        .WithMany("Categories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_service");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.Services.Infrastructure.Persistence.Models.ServiceModel", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
