// <auto-generated />
using System;
using CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CompanyProfileDbContext))]
    [Migration("20260819184317_InitialCompanyProfileSchema")]
    partial class InitialCompanyProfileSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("company_profile")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.CompanyProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("SingletonKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("singleton_key");

                    b.HasKey("Id")
                        .HasName("pk_company_profile");

                    b.HasIndex("SingletonKey")
                        .IsUnique()
                        .HasDatabaseName("uq_company_profile_singleton_key");

                    b.ToTable("company_profile", "company_profile", t =>
                        {
                            t.HasCheckConstraint("ck_company_profile_singleton_key", "singleton_key = 1");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.EmailModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_profile_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_email");

                    b.HasIndex("CompanyProfileId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_email_company_profile_id_type");

                    b.ToTable("email", "company_profile", t =>
                        {
                            t.HasCheckConstraint("ck_email_address", "length(btrim(address)) > 0");

                            t.HasCheckConstraint("ck_email_type", "type IN ('PUBLIC', 'CONTACT_REQUEST_RECIPIENT')");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.LocationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_profile_id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("CompanyProfileId")
                        .IsUnique()
                        .HasDatabaseName("uq_location_company_profile_id");

                    b.ToTable("location", "company_profile", t =>
                        {
                            t.HasCheckConstraint("ck_location_address", "length(btrim(address)) > 0");

                            t.HasCheckConstraint("ck_location_coordinates_pair", "(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)");

                            t.HasCheckConstraint("ck_location_latitude", "latitude IS NULL OR latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_location_longitude", "longitude IS NULL OR longitude BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.PhoneModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_profile_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_phone");

                    b.HasIndex("CompanyProfileId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_phone_company_profile_id_type");

                    b.ToTable("phone", "company_profile", t =>
                        {
                            t.HasCheckConstraint("ck_phone_number", "length(btrim(number)) > 0");

                            t.HasCheckConstraint("ck_phone_type", "type IN ('PHONE', 'WHATSAPP')");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.SocialLinkModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_profile_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("network");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_social_link");

                    b.HasIndex("CompanyProfileId", "Network")
                        .IsUnique()
                        .HasDatabaseName("uq_social_link_company_profile_id_network");

                    b.ToTable("social_link", "company_profile", t =>
                        {
                            t.HasCheckConstraint("ck_social_link_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_social_link_network", "length(btrim(network)) > 0");

                            t.HasCheckConstraint("ck_social_link_url", "length(btrim(url)) > 0");
                        });
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.EmailModel", b =>
                {
                    b.HasOne("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.CompanyProfileModel", "CompanyProfile")
                        .WithMany("Emails")
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_company_profile");

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.LocationModel", b =>
                {
                    b.HasOne("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.CompanyProfileModel", "CompanyProfile")
                        .WithOne("Location")
                        .HasForeignKey("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.LocationModel", "CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_location_company_profile");

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.PhoneModel", b =>
                {
                    b.HasOne("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.CompanyProfileModel", "CompanyProfile")
                        .WithMany("Phones")
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phone_company_profile");

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.SocialLinkModel", b =>
                {
                    b.HasOne("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.CompanyProfileModel", "CompanyProfile")
                        .WithMany("SocialLinks")
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_link_company_profile");

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("CromaticaCreativa.Modules.CompanyProfile.Infrastructure.Persistence.Models.CompanyProfileModel", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Location");

                    b.Navigation("Phones");

                    b.Navigation("SocialLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
